# Generated by Django 2.0.3 on 2020-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('faculty', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField()),
                ('fee', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.IntegerField(unique=True)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
